# Generated by Django 4.0.4 on 2022-05-26 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('otros_nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('perfil', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacante', models.SmallIntegerField()),
                ('salario', models.FloatField()),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPage.candidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPage.oferta')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='postulado',
            field=models.ManyToManyField(through='webPage.Postulados', to='webPage.candidato'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.tipocontrato'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ciudad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.ciudad'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.tipo_doc'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postulados',
            constraint=models.UniqueConstraint(fields=('candidato', 'oferta'), name='unique_offer'),
        ),
    ]
