# Generated by Django 4.0.4 on 2022-05-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('CP', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vacante', models.IntegerField(max_length=3)),
                ('salario', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_doc', models.IntegerField(max_length=20)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=20)),
                ('perfil', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('ciudad', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.ciudad')),
                ('tipo_doc_tipo', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.tipo_doc')),
            ],
        ),
    ]
