# Generated by Django 4.0.4 on 2022-05-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='candidato',
            name='apellido2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='numero_doc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tipo_doc',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_contrato',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.tipo_contrato'),
        ),
    ]
