# Generated by Django 4.0.4 on 2022-05-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0002_tipo_contrato_alter_candidato_apellido2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
