# Generated by Django 4.0.4 on 2022-05-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0003_candidato_foto_oferta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='estado',
        ),
    ]
