# Generated by Django 4.0.4 on 2022-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0005_candidato_foto_oferta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='postulados',
            field=models.ManyToManyField(to='webPage.candidato'),
        ),
    ]
