# Generated by Django 4.0.4 on 2022-05-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0006_oferta_postulados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='numero_doc',
            new_name='numero_documento',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='nombre2',
            new_name='otros_nombres',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='nombre1',
            new_name='primer_nombre',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='tipo_doc_tipo',
            new_name='tipo_documento',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='CP',
            new_name='codigo_postal',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='salario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='vacante',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tipo_doc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_contrato',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.tipocontrato'),
        ),
        migrations.DeleteModel(
            name='Tipo_Contrato',
        ),
    ]
