# Generated by Django 4.0.4 on 2022-05-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0007_tipocontrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPage.candidato')),
            ],
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='postulados',
        ),
        migrations.AddField(
            model_name='oferta',
            name='postulado',
            field=models.ManyToManyField(through='webPage.Postulados', to='webPage.candidato'),
        ),
        migrations.AddField(
            model_name='postulados',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPage.oferta'),
        ),
    ]
