# Generated by Django 4.0.4 on 2022-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0008_postulados_remove_oferta_postulados_oferta_postulado_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postulados',
            constraint=models.UniqueConstraint(fields=('candidato', 'oferta'), name='unique_offer'),
        ),
    ]
